const data = {
    products:[
        {
            name:"Shirt",
            brand:"Nike",
            slug:'nike-shirt',
            price:450,
            image:"https://image.uniqlo.com/UQ/ST3/ph/imagesgoods/446935/item/phgoods_41_446935.jpg?width=1008&impolicy=quality_75"
        },
        {
            name:"T-Shirt",
            brand:"Adidas",
            slug:'adidas-t-shirt',
            price:450,
            image:"https://image.uniqlo.com/UQ/ST3/ph/imagesgoods/446935/item/phgoods_41_446935.jpg?width=1008&impolicy=quality_75"
        },
        {
            name:"Jersey",
            brand:"Nike",
            slug:'nike-jersey',
            price:450,
            image:"https://image.uniqlo.com/UQ/ST3/ph/imagesgoods/446935/item/phgoods_41_446935.jpg?width=1008&impolicy=quality_75"
        },
        {
            name:"Shoes",
            brand:"Nike",
            slug:'nike-shoes',
            price:450,
            image:"https://image.uniqlo.com/UQ/ST3/ph/imagesgoods/446935/item/phgoods_41_446935.jpg?width=1008&impolicy=quality_75"
        },
        {
            name:"Jeans",
            brand:"Levi",
            slug:'levi-jeans',
            price:450,
            image:"https://image.uniqlo.com/UQ/ST3/ph/imagesgoods/446935/item/phgoods_41_446935.jpg?width=1008&impolicy=quality_75"
        }
    ]
}
export default data;